from strands import Agent, tool
from strands.models import BedrockModel
from pydantic import BaseModel, Field
from typing import List, Dict

# ==========================
# Structured output models
# ==========================
class ClientKPI(BaseModel):
    client_name: str = Field(description="Name of the client")
    monthly_revenue: float = Field(description="Revenue generated by the client in a month")
    engagement_score: int = Field(ge=1, le=10, description="Client engagement score from 1 (low) to 10 (high)")
    support_tickets: int = Field(description="Number of support tickets logged by the client")
    churn_risk: str = Field(description="Risk of churn: Low, Medium, High")

class ClientPerformanceReport(BaseModel):
    total_clients: int = Field(description="Total number of clients")
    top_clients: List[ClientKPI] = Field(description="List of top-performing clients")
    at_risk_clients: List[ClientKPI] = Field(description="List of clients at risk of churn")
    summary: str = Field(description="Summary of overall client performance and recommendations")

# ==========================
# System prompt
# ==========================
CLIENT_PERFORMANCE_PROMPT = """
You are an MSP client performance analyst. Your task is to evaluate client profitability, engagement, and churn risk.

When analyzing clients:
1. Identify top-performing clients based on revenue and engagement.
2. Detect clients at risk of churn based on low engagement or high support tickets.
3. Provide structured output in ClientPerformanceReport format.
4. Include actionable recommendations to improve client retention and revenue.
5. Maintain a professional, analytical tone.
"""

# ==========================
# Bedrock model
# ==========================
bedrock_model = BedrockModel(
    model_id="us.anthropic.claude-3-7-sonnet-20250219-v1:0",
    region_name="us-west-2",
    temperature=0.0,  # deterministic outputs for analytics
)

# ==========================
# Tools / helper functions
# ==========================
@tool
def analyze_client_performance(clients_data: List[Dict]) -> ClientPerformanceReport:
    """
    Analyze MSP client performance.
    clients_data: List of dicts, each with keys: client_name, monthly_revenue, engagement_score, support_tickets
    """
    top_clients = []
    at_risk_clients = []

    for client in clients_data:
        # Sample logic for demonstration
        kpi = ClientKPI(
            client_name=client["client_name"],
            monthly_revenue=client["monthly_revenue"],
            engagement_score=client["engagement_score"],
            support_tickets=client["support_tickets"],
            churn_risk="High" if client["engagement_score"] <= 3 or client["support_tickets"] > 10 else "Low"
        )
        if client["monthly_revenue"] >= 5000 and client["engagement_score"] >= 7:
            top_clients.append(kpi)
        if kpi.churn_risk == "High":
            at_risk_clients.append(kpi)

    summary = f"Out of {len(clients_data)} clients, {len(top_clients)} are top-performing, and {len(at_risk_clients)} are at risk of churn. Focus on improving engagement and support experience for at-risk clients."

    return ClientPerformanceReport(
        total_clients=len(clients_data),
        top_clients=top_clients,
        at_risk_clients=at_risk_clients,
        summary=summary
    )

# ==========================
# Client Performance Agent
# ==========================
client_performance_agent = Agent(
    model=bedrock_model,
    system_prompt=CLIENT_PERFORMANCE_PROMPT,
    tools=[analyze_client_performance],
    callback_handler=None,
)

# ==========================
# Testing
# ==========================
if __name__ == "__main__":
    demo_clients = [
        {"client_name": "Client A", "monthly_revenue": 8000, "engagement_score": 9, "support_tickets": 2},
        {"client_name": "Client B", "monthly_revenue": 2000, "engagement_score": 3, "support_tickets": 12},
        {"client_name": "Client C", "monthly_revenue": 4000, "engagement_score": 6, "support_tickets": 5},
    ]

    report = analyze_client_performance(demo_clients)
    
    print(f"Total Clients: {report.total_clients}")
    print("\nTop Clients:")
    for c in report.top_clients:
        print(f"• {c.client_name} - Revenue: ${c.monthly_revenue}, Engagement: {c.engagement_score}/10")
    print("\nAt-Risk Clients:")
    for c in report.at_risk_clients:
        print(f"• {c.client_name} - Revenue: ${c.monthly_revenue}, Engagement: {c.engagement_score}/10, Churn Risk: {c.churn_risk}")
    print(f"\nSummary:\n{report.summary}")
